language: minimal
sudo: required
os: linux
dist: bionic
      
script: ./autogen.sh && ./configure && sudo make install -j4 && cd pmemcheck/pmat_tests && make && valgrind --tool=pmemcheck --pmat-verifier=in-order-store_verifier ./in-order-store && valgrind --tool=pmemcheck --pmat-verifier=in-order-store_verifier ./out-of-order-store && valgrind --tool=pmemcheck --pmat-verifier=openmp_test_verifier ./openmp_test && make clean && cd microbenchmarks/durable_queue && make && valgrind --tool=pmemcheck --pmat-verifier=durable_queue_verifier ./durable_queue 5 && make clean && cd ../linked_list && valgrind --tool=pmemcheck --pmat-verifier=linked_list_verifier ./linked_list g 1024 && valgrind --tool=pmemcheck --pmat-verifier=linked_list_verifier ./linked_list b 1024 && make clean
