name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for taking the time to try out the Persistent Memory Analysis Tool (PMAT); I will try to address this issue as soon as possible.'
        pr-message: 'Thank you for your potential contribution to the Persistent Memory Analysis Tool (PMAT); I will try to review this PR as soon as possible.'
